### ISSUE TITLE
Netflow

### ISSUE THREAD

**Issue by CyberAbwehr** [epacke/logstash-pipeline-tester#279]
It is possible to send Netflow information direct to Logstash-pipeline-tester, without putting some source information into the GUI (raw pipeline data)?

best regards

**Comment by epacke** [comment]
Yep, that should be possible. Just create the input, pipeline and keep the output to the default one for the tool. Then expose the input port and send the data to the container ip. 👍🏻

**Comment by CyberAbwehr** [comment]
Hi,

I have test it now and it does not work.

I use at the moment logstash 8.9.2

So I modify the file:

**logstash/Dockerfile
FROM logstash:8.9.2**


**docker-compose.yml**

```
services:
  pipeline-ui:
    build: "./pipeline-ui"
    container_name: "config_tester"
    environment:
      LOG_LEVEL: warn
    ports:
      - "8080:8080"
    volumes:
      - "./logstash/logstash-config/pipeline:/usr/src/pipeline"
  logstash:
    build: "./logstash"
    container_name: "logstash"
    hostname: "logstash"
    environment:
      BACKEND_ENDPOINT: "${BACKEND_ENDPOINT:-http://pipeline-ui:8080/api/v1/receiveLogstashOutput}"
    ports:
      - "5245:5245"
      - "9600:9600"
      - "5060:5060"
      - "2055:2055"
    volumes:
      - "./logstash/logstash-config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "./logstash/logstash-config/pipelines.yml:/usr/share/logstash/config/pipelines.yml"
      - "./logstash/logstash-config/pipeline:/usr/share/logstash/pipeline"
      - "./logstash/logstash-config/dictionaries:/usr/share/logstash/dictionaries"
      - "./logstash/logstash-config/patterns:/usr/share/logstash/patterns"

```
after that i run docker-compose build

**pipelines.yml**

```
- pipeline.id: f5-syslog
  path.config: "/usr/share/logstash/pipeline/f5-syslog"
- pipeline.id: generic-json
  path.config: "/usr/share/logstash/pipeline/generic-json"
- pipeline.id: netflow
  path.config: "/usr/share/logstash/pipeline/netflow"
```

**input.conf**

```
input {
  # Netflow
  udp {
    port => 2055
    codec => netflow {
      versions => [5,9,10]
      include_flowset_id => "true"
    }
    type => "netflow"
  }
}
```


**output.conf**

```
output {
    http {
        format => "json"
        http_method => "post"
        url => "${BACKEND_ENDPOINT:http://pipeline-ui:8080/api/v1/receiveLogstashOutput}"
    }
}
```

In the gui i select the netflow pipline and i press SEND

docker logs logstash

```
logstash       | [2025-02-13T11:11:01,033][WARN ][logstash.codecs.netflow  ][netflow][de7fc1c6e35ab62c7c35337a9dd7e741ec389b378c3e1bf0f254c8af336e091b] Invalid netflow packet received (data truncated)
```

For me this is a correct output, because there where no information in the field "raw pipline data" in the GUI

I have test the tool flowgen with logstash and opensearch and it works on my test lab and ist works.
So i use it also with the logstash-pipline-tester and send netflow information to the port 2055

```
./flowgen -n3000 -i50 -w1 -p2055 192.168.56.106
```

I cant check if it send the information to the BACKEND_ENDPOINT automatic without pressing the bottom SEND.

At the moment it does not work.

I think it is a problem with the flag 
http_method => "post"
The GUI is waiting for a POST and the POST I think will come with pressing the bottom SEND in the GUI.

Could this be the problem?
